################################################################################
# For development mode, this docker-compose file uses:
# - network_mode: 'host'
#
# This is needed because in site.conf
# there is the configuration: localhost:8080/api
#
# With this, this container can access to your local API if your application
# is started under localhost:8080
#
# You can comment:
# - network_mode: 'host'
#
################################################################################
version: '3'
services:
    chirpstack-nginx:
        image: nginx:1.19-alpine
        volumes:
        - ./configuration/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./configuration/nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
        - "80:80"
        - "443:443"
    #    network_mode: 'host'
